// Generated by scripts/gen-types.py — do not edit by hand.
// Regenerate after every migration phase (docs/dev/local-stack.md).

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      access_credentials: {
        Row: {
          id: string;
          operator_id: string;
          property_id: string;
          entry_method: Database["public"]["Enums"]["entry_method"];
          ciphertext: string;
          label: string | null;
          rotated_at: string | null;
          revoked_at: string | null;
          created_at: string;
          updated_at: string;
          key_id: string | null;
        };
        Insert: {
          id?: string;
          operator_id: string;
          property_id: string;
          entry_method: Database["public"]["Enums"]["entry_method"];
          ciphertext: string;
          label?: string | null;
          rotated_at?: string | null;
          revoked_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          operator_id?: string;
          property_id?: string;
          entry_method?: Database["public"]["Enums"]["entry_method"];
          ciphertext?: string;
          label?: string | null;
          rotated_at?: string | null;
          revoked_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      clients: {
        Row: {
          id: string;
          operator_id: string;
          auth_user_id: string | null;
          full_name: string;
          email: string | null;
          phone: string | null;
          status: Database["public"]["Enums"]["client_status"];
          notes: string | null;
          invite_token: string;
          stripe_customer_id: string | null;
          plan_id: string | null;
          subscription_status: Database["public"]["Enums"]["subscription_status"];
          stripe_subscription_id: string | null;
          credit_balance: number;
          created_at: string;
          updated_at: string;
          current_period_end: string | null;
          unsubscribe_token: string;
          invite_expires_at: string | null;
          invite_revoked_at: string | null;
          purged_at: string | null;
          notice_accepted_at: string | null;
          notice_version: string | null;
        };
        Insert: {
          id?: string;
          operator_id: string;
          auth_user_id?: string | null;
          full_name: string;
          email?: string | null;
          phone?: string | null;
          status?: Database["public"]["Enums"]["client_status"];
          notes?: string | null;
          invite_token?: string;
          stripe_customer_id?: string | null;
          plan_id?: string | null;
          subscription_status?: Database["public"]["Enums"]["subscription_status"];
          stripe_subscription_id?: string | null;
          credit_balance?: number;
          created_at?: string;
          updated_at?: string;
          current_period_end?: string | null;
          unsubscribe_token?: string;
          invite_expires_at?: string | null;
          invite_revoked_at?: string | null;
          purged_at?: string | null;
          notice_accepted_at?: string | null;
          notice_version?: string | null;
        };
        Update: {
          id?: string;
          operator_id?: string;
          auth_user_id?: string | null;
          full_name?: string;
          email?: string | null;
          phone?: string | null;
          status?: Database["public"]["Enums"]["client_status"];
          notes?: string | null;
          invite_token?: string;
          stripe_customer_id?: string | null;
          plan_id?: string | null;
          subscription_status?: Database["public"]["Enums"]["subscription_status"];
          stripe_subscription_id?: string | null;
          credit_balance?: number;
          created_at?: string;
          updated_at?: string;
          current_period_end?: string | null;
          unsubscribe_token?: string;
          invite_expires_at?: string | null;
          invite_revoked_at?: string | null;
          purged_at?: string | null;
          notice_accepted_at?: string | null;
          notice_version?: string | null;
        };
        Relationships: [];
      };
      credential_access_log: {
        Row: {
          id: string;
          operator_id: string;
          credential_id: string;
          accessed_by: string;
          purpose: string | null;
          accessed_at: string;
          created_at: string;
          action: Database["public"]["Enums"]["credential_action"];
          ip: unknown | null;
          user_agent: string | null;
          walk_id: string | null;
        };
        Insert: {
          id?: string;
          operator_id: string;
          credential_id: string;
          accessed_by: string;
          purpose?: string | null;
          accessed_at?: string;
          created_at?: string;
          action?: Database["public"]["Enums"]["credential_action"];
          ip?: unknown | null;
          user_agent?: string | null;
          walk_id?: string | null;
        };
        Update: {
          id?: string;
          operator_id?: string;
          credential_id?: string;
          accessed_by?: string;
          purpose?: string | null;
          accessed_at?: string;
          created_at?: string;
          action?: Database["public"]["Enums"]["credential_action"];
          ip?: unknown | null;
          user_agent?: string | null;
          walk_id?: string | null;
        };
        Relationships: [];
      };
      credit_ledger: {
        Row: {
          id: string;
          seq: number;
          operator_id: string;
          client_id: string;
          entry_type: Database["public"]["Enums"]["ledger_entry_type"];
          amount: number;
          balance_after: number;
          walk_id: string | null;
          expires_at: string | null;
          note: string | null;
          created_at: string;
          stripe_invoice_id: string | null;
        };
        Insert: {
          id?: string;
          operator_id: string;
          client_id: string;
          entry_type: Database["public"]["Enums"]["ledger_entry_type"];
          amount: number;
          balance_after: number;
          walk_id?: string | null;
          expires_at?: string | null;
          note?: string | null;
          created_at?: string;
          stripe_invoice_id?: string | null;
        };
        Update: {
          id?: string;
          operator_id?: string;
          client_id?: string;
          entry_type?: Database["public"]["Enums"]["ledger_entry_type"];
          amount?: number;
          balance_after?: number;
          walk_id?: string | null;
          expires_at?: string | null;
          note?: string | null;
          created_at?: string;
          stripe_invoice_id?: string | null;
        };
        Relationships: [];
      };
      email_suppressions: {
        Row: {
          id: string;
          email: string;
          operator_id: string | null;
          notification_type: Database["public"]["Enums"]["notification_type"] | null;
          reason: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          operator_id?: string | null;
          notification_type?: Database["public"]["Enums"]["notification_type"] | null;
          reason: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          operator_id?: string | null;
          notification_type?: Database["public"]["Enums"]["notification_type"] | null;
          reason?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      invite_claim_attempts: {
        Row: {
          id: string;
          operator_id: string;
          client_id: string;
          attempted_by: string | null;
          attempted_email: string | null;
          outcome: Database["public"]["Enums"]["invite_claim_outcome"];
          created_at: string;
        };
        Insert: {
          id?: string;
          operator_id: string;
          client_id: string;
          attempted_by?: string | null;
          attempted_email?: string | null;
          outcome: Database["public"]["Enums"]["invite_claim_outcome"];
          created_at?: string;
        };
        Update: {
          id?: string;
          operator_id?: string;
          client_id?: string;
          attempted_by?: string | null;
          attempted_email?: string | null;
          outcome?: Database["public"]["Enums"]["invite_claim_outcome"];
          created_at?: string;
        };
        Relationships: [];
      };
      invite_signup_attempts: {
        Row: {
          id: string;
          client_id: string;
          ip: unknown | null;
          attempted_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          ip?: unknown | null;
          attempted_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          ip?: unknown | null;
          attempted_at?: string;
        };
        Relationships: [];
      };
      job_runs: {
        Row: {
          id: string;
          job_name: string;
          started_at: string;
          finished_at: string | null;
          ok: boolean;
          detail: Json;
          error: string | null;
        };
        Insert: {
          id?: string;
          job_name: string;
          started_at?: string;
          finished_at?: string | null;
          ok?: boolean;
          detail?: Json;
          error?: string | null;
        };
        Update: {
          id?: string;
          job_name?: string;
          started_at?: string;
          finished_at?: string | null;
          ok?: boolean;
          detail?: Json;
          error?: string | null;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          operator_id: string;
          client_id: string | null;
          type: Database["public"]["Enums"]["notification_type"];
          title: string;
          body: string | null;
          walk_id: string | null;
          read_at: string | null;
          created_at: string;
          updated_at: string;
          email_status: Database["public"]["Enums"]["email_delivery_status"];
          email_attempts: number;
          email_sent_at: string | null;
          email_last_error: string | null;
          push_status: Database["public"]["Enums"]["push_delivery_status"];
          push_attempts: number;
          push_sent_at: string | null;
          push_last_error: string | null;
          email_claimed_at: string | null;
          push_claimed_at: string | null;
          email_claim_token: string | null;
          push_claim_token: string | null;
        };
        Insert: {
          id?: string;
          operator_id: string;
          client_id?: string | null;
          type: Database["public"]["Enums"]["notification_type"];
          title: string;
          body?: string | null;
          walk_id?: string | null;
          read_at?: string | null;
          created_at?: string;
          updated_at?: string;
          email_status?: Database["public"]["Enums"]["email_delivery_status"];
          email_attempts?: number;
          email_sent_at?: string | null;
          email_last_error?: string | null;
          push_status?: Database["public"]["Enums"]["push_delivery_status"];
          push_attempts?: number;
          push_sent_at?: string | null;
          push_last_error?: string | null;
          email_claimed_at?: string | null;
          push_claimed_at?: string | null;
          email_claim_token?: string | null;
          push_claim_token?: string | null;
        };
        Update: {
          id?: string;
          operator_id?: string;
          client_id?: string | null;
          type?: Database["public"]["Enums"]["notification_type"];
          title?: string;
          body?: string | null;
          walk_id?: string | null;
          read_at?: string | null;
          created_at?: string;
          updated_at?: string;
          email_status?: Database["public"]["Enums"]["email_delivery_status"];
          email_attempts?: number;
          email_sent_at?: string | null;
          email_last_error?: string | null;
          push_status?: Database["public"]["Enums"]["push_delivery_status"];
          push_attempts?: number;
          push_sent_at?: string | null;
          push_last_error?: string | null;
          email_claimed_at?: string | null;
          push_claimed_at?: string | null;
          email_claim_token?: string | null;
          push_claim_token?: string | null;
        };
        Relationships: [];
      };
      operators: {
        Row: {
          id: string;
          business_name: string;
          display_name: string;
          email: string;
          phone: string | null;
          timezone: string;
          currency: string;
          low_credit_threshold: number;
          created_at: string;
          updated_at: string;
          cancellation_cutoff_hours: number;
          stripe_account_id: string | null;
          stripe_charges_enabled: boolean;
          stripe_payouts_enabled: boolean;
          stripe_details_submitted: boolean;
          stripe_account_connected_at: string | null;
          gps_retention_days: number;
          terms_accepted_at: string | null;
          terms_version: string | null;
          trial_ends_at: string;
          platform_customer_id: string | null;
          platform_subscription_id: string | null;
          platform_subscription_status: Database["public"]["Enums"]["subscription_status"];
          checkout_mint_claimed_at: string | null;
        };
        Insert: {
          id: string;
          business_name: string;
          display_name: string;
          email: string;
          phone?: string | null;
          timezone?: string;
          currency?: string;
          low_credit_threshold?: number;
          created_at?: string;
          updated_at?: string;
          cancellation_cutoff_hours?: number;
          stripe_account_id?: string | null;
          stripe_charges_enabled?: boolean;
          stripe_payouts_enabled?: boolean;
          stripe_details_submitted?: boolean;
          stripe_account_connected_at?: string | null;
          gps_retention_days?: number;
          terms_accepted_at?: string | null;
          terms_version?: string | null;
          trial_ends_at?: string;
          platform_customer_id?: string | null;
          platform_subscription_id?: string | null;
          platform_subscription_status?: Database["public"]["Enums"]["subscription_status"];
          checkout_mint_claimed_at?: string | null;
        };
        Update: {
          id?: string;
          business_name?: string;
          display_name?: string;
          email?: string;
          phone?: string | null;
          timezone?: string;
          currency?: string;
          low_credit_threshold?: number;
          created_at?: string;
          updated_at?: string;
          cancellation_cutoff_hours?: number;
          stripe_account_id?: string | null;
          stripe_charges_enabled?: boolean;
          stripe_payouts_enabled?: boolean;
          stripe_details_submitted?: boolean;
          stripe_account_connected_at?: string | null;
          gps_retention_days?: number;
          terms_accepted_at?: string | null;
          terms_version?: string | null;
          trial_ends_at?: string;
          platform_customer_id?: string | null;
          platform_subscription_id?: string | null;
          platform_subscription_status?: Database["public"]["Enums"]["subscription_status"];
          checkout_mint_claimed_at?: string | null;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          operator_id: string;
          client_id: string;
          walk_id: string | null;
          type: Database["public"]["Enums"]["payment_type"];
          amount_pence: number;
          currency: string;
          stripe_payment_intent_id: string | null;
          stripe_invoice_id: string | null;
          status: Database["public"]["Enums"]["payment_status"];
          receipt_url: string | null;
          created_at: string;
          updated_at: string;
          refunded_amount_pence: number;
          reversed_at: string | null;
          reversal_reason: string | null;
          credits_reversed: number;
          credits_unrecovered: number;
          reversal_needs_review: boolean;
          stripe_charge_id: string | null;
          superseded_at: string | null;
        };
        Insert: {
          id?: string;
          operator_id: string;
          client_id: string;
          walk_id?: string | null;
          type: Database["public"]["Enums"]["payment_type"];
          amount_pence: number;
          currency?: string;
          stripe_payment_intent_id?: string | null;
          stripe_invoice_id?: string | null;
          status: Database["public"]["Enums"]["payment_status"];
          receipt_url?: string | null;
          created_at?: string;
          updated_at?: string;
          refunded_amount_pence?: number;
          reversed_at?: string | null;
          reversal_reason?: string | null;
          credits_reversed?: number;
          credits_unrecovered?: number;
          reversal_needs_review?: boolean;
          stripe_charge_id?: string | null;
          superseded_at?: string | null;
        };
        Update: {
          id?: string;
          operator_id?: string;
          client_id?: string;
          walk_id?: string | null;
          type?: Database["public"]["Enums"]["payment_type"];
          amount_pence?: number;
          currency?: string;
          stripe_payment_intent_id?: string | null;
          stripe_invoice_id?: string | null;
          status?: Database["public"]["Enums"]["payment_status"];
          receipt_url?: string | null;
          created_at?: string;
          updated_at?: string;
          refunded_amount_pence?: number;
          reversed_at?: string | null;
          reversal_reason?: string | null;
          credits_reversed?: number;
          credits_unrecovered?: number;
          reversal_needs_review?: boolean;
          stripe_charge_id?: string | null;
          superseded_at?: string | null;
        };
        Relationships: [];
      };
      pets: {
        Row: {
          id: string;
          operator_id: string;
          client_id: string;
          name: string;
          breed: string | null;
          size: Database["public"]["Enums"]["pet_size"] | null;
          temperament: string | null;
          medical_notes: string | null;
          feeding_notes: string | null;
          medication_notes: string | null;
          vet_name: string | null;
          vet_phone: string | null;
          is_reactive: boolean;
          is_escape_risk: boolean;
          photo_path: string | null;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          operator_id: string;
          client_id: string;
          name: string;
          breed?: string | null;
          size?: Database["public"]["Enums"]["pet_size"] | null;
          temperament?: string | null;
          medical_notes?: string | null;
          feeding_notes?: string | null;
          medication_notes?: string | null;
          vet_name?: string | null;
          vet_phone?: string | null;
          is_reactive?: boolean;
          is_escape_risk?: boolean;
          photo_path?: string | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          operator_id?: string;
          client_id?: string;
          name?: string;
          breed?: string | null;
          size?: Database["public"]["Enums"]["pet_size"] | null;
          temperament?: string | null;
          medical_notes?: string | null;
          feeding_notes?: string | null;
          medication_notes?: string | null;
          vet_name?: string | null;
          vet_phone?: string | null;
          is_reactive?: boolean;
          is_escape_risk?: boolean;
          photo_path?: string | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      plan_change_intents: {
        Row: {
          id: string;
          operator_id: string;
          client_id: string;
          requested_by: string;
          old_plan_id: string | null;
          new_plan_id: string;
          stripe_subscription_id: string | null;
          stripe_update_idempotency_key: string;
          remaining_fraction: number;
          status: string;
          stripe_event_id: string | null;
          requested_at: string;
          applied_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          operator_id: string;
          client_id: string;
          requested_by: string;
          old_plan_id?: string | null;
          new_plan_id: string;
          stripe_subscription_id?: string | null;
          stripe_update_idempotency_key: string;
          remaining_fraction: number;
          status?: string;
          stripe_event_id?: string | null;
          requested_at?: string;
          applied_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          operator_id?: string;
          client_id?: string;
          requested_by?: string;
          old_plan_id?: string | null;
          new_plan_id?: string;
          stripe_subscription_id?: string | null;
          stripe_update_idempotency_key?: string;
          remaining_fraction?: number;
          status?: string;
          stripe_event_id?: string | null;
          requested_at?: string;
          applied_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      plans: {
        Row: {
          id: string;
          operator_id: string;
          name: string;
          credits_per_cycle: number;
          price_pence: number;
          cycle: Database["public"]["Enums"]["billing_cycle"];
          rollover_policy: Database["public"]["Enums"]["rollover_policy"];
          rollover_cap: number | null;
          rollover_expiry_days: number | null;
          overage_rate_pence: number;
          stripe_price_id: string | null;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          operator_id: string;
          name: string;
          credits_per_cycle: number;
          price_pence: number;
          cycle: Database["public"]["Enums"]["billing_cycle"];
          rollover_policy?: Database["public"]["Enums"]["rollover_policy"];
          rollover_cap?: number | null;
          rollover_expiry_days?: number | null;
          overage_rate_pence: number;
          stripe_price_id?: string | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          operator_id?: string;
          name?: string;
          credits_per_cycle?: number;
          price_pence?: number;
          cycle?: Database["public"]["Enums"]["billing_cycle"];
          rollover_policy?: Database["public"]["Enums"]["rollover_policy"];
          rollover_cap?: number | null;
          rollover_expiry_days?: number | null;
          overage_rate_pence?: number;
          stripe_price_id?: string | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      properties: {
        Row: {
          id: string;
          operator_id: string;
          client_id: string;
          label: string;
          address_line1: string | null;
          address_line2: string | null;
          city: string | null;
          postcode: string | null;
          access_notes_public: string | null;
          lat: number | null;
          lng: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          operator_id: string;
          client_id: string;
          label: string;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          postcode?: string | null;
          access_notes_public?: string | null;
          lat?: number | null;
          lng?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          operator_id?: string;
          client_id?: string;
          label?: string;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          postcode?: string | null;
          access_notes_public?: string | null;
          lat?: number | null;
          lng?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      push_subscriptions: {
        Row: {
          id: string;
          operator_id: string;
          client_id: string | null;
          endpoint: string;
          p256dh: string;
          auth: string;
          user_agent: string | null;
          created_at: string;
          last_seen_at: string;
          failure_count: number;
          last_failure_at: string | null;
          last_error: string | null;
        };
        Insert: {
          id?: string;
          operator_id: string;
          client_id?: string | null;
          endpoint: string;
          p256dh: string;
          auth: string;
          user_agent?: string | null;
          created_at?: string;
          last_seen_at?: string;
          failure_count?: number;
          last_failure_at?: string | null;
          last_error?: string | null;
        };
        Update: {
          id?: string;
          operator_id?: string;
          client_id?: string | null;
          endpoint?: string;
          p256dh?: string;
          auth?: string;
          user_agent?: string | null;
          created_at?: string;
          last_seen_at?: string;
          failure_count?: number;
          last_failure_at?: string | null;
          last_error?: string | null;
        };
        Relationships: [];
      };
      recurring_schedules: {
        Row: {
          id: string;
          operator_id: string;
          client_id: string;
          property_id: string;
          service_type_id: string;
          days_of_week: number[];
          window_start: string;
          window_end: string;
          start_date: string;
          end_date: string | null;
          paused_from: string | null;
          paused_until: string | null;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          operator_id: string;
          client_id: string;
          property_id: string;
          service_type_id: string;
          days_of_week: number[];
          window_start: string;
          window_end: string;
          start_date: string;
          end_date?: string | null;
          paused_from?: string | null;
          paused_until?: string | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          operator_id?: string;
          client_id?: string;
          property_id?: string;
          service_type_id?: string;
          days_of_week?: number[];
          window_start?: string;
          window_end?: string;
          start_date?: string;
          end_date?: string | null;
          paused_from?: string | null;
          paused_until?: string | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      schedule_pets: {
        Row: {
          schedule_id: string;
          pet_id: string;
          operator_id: string;
          created_at: string;
        };
        Insert: {
          schedule_id: string;
          pet_id: string;
          operator_id: string;
          created_at?: string;
        };
        Update: {
          schedule_id?: string;
          pet_id?: string;
          operator_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      service_types: {
        Row: {
          id: string;
          operator_id: string;
          name: string;
          duration_minutes: number;
          credit_cost: number;
          weekend_surcharge_credits: number;
          is_default: boolean;
          created_at: string;
          updated_at: string;
          visit_price_pence: number | null;
        };
        Insert: {
          id?: string;
          operator_id: string;
          name: string;
          duration_minutes: number;
          credit_cost: number;
          weekend_surcharge_credits?: number;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
          visit_price_pence?: number | null;
        };
        Update: {
          id?: string;
          operator_id?: string;
          name?: string;
          duration_minutes?: number;
          credit_cost?: number;
          weekend_surcharge_credits?: number;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
          visit_price_pence?: number | null;
        };
        Relationships: [];
      };
      stripe_events: {
        Row: {
          id: string;
          type: string;
          payload: Json | null;
          processed_at: string;
          created_at: string;
          status: string;
          claimed_at: string;
        };
        Insert: {
          id: string;
          type: string;
          payload?: Json | null;
          processed_at?: string;
          created_at?: string;
          status?: string;
          claimed_at?: string;
        };
        Update: {
          id?: string;
          type?: string;
          payload?: Json | null;
          processed_at?: string;
          created_at?: string;
          status?: string;
          claimed_at?: string;
        };
        Relationships: [];
      };
      vault_canary: {
        Row: {
          id: boolean;
          ciphertext: string;
          key_id: string | null;
          updated_at: string;
        };
        Insert: {
          id?: boolean;
          ciphertext: string;
          updated_at?: string;
        };
        Update: {
          id?: boolean;
          ciphertext?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      vault_rate_limit_attempts: {
        Row: {
          id: string;
          user_id: string;
          ip: unknown | null;
          attempted_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          ip?: unknown | null;
          attempted_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          ip?: unknown | null;
          attempted_at?: string;
        };
        Relationships: [];
      };
      walk_gps_points: {
        Row: {
          id: string;
          walk_id: string;
          operator_id: string;
          recorded_at: string;
          lat: number;
          lng: number;
          accuracy_m: number | null;
          created_at: string;
          gap_before: boolean;
        };
        Insert: {
          id?: string;
          walk_id: string;
          operator_id: string;
          recorded_at: string;
          lat: number;
          lng: number;
          accuracy_m?: number | null;
          created_at?: string;
          gap_before?: boolean;
        };
        Update: {
          id?: string;
          walk_id?: string;
          operator_id?: string;
          recorded_at?: string;
          lat?: number;
          lng?: number;
          accuracy_m?: number | null;
          created_at?: string;
          gap_before?: boolean;
        };
        Relationships: [];
      };
      walk_pets: {
        Row: {
          walk_id: string;
          pet_id: string;
          operator_id: string;
          created_at: string;
        };
        Insert: {
          walk_id: string;
          pet_id: string;
          operator_id: string;
          created_at?: string;
        };
        Update: {
          walk_id?: string;
          pet_id?: string;
          operator_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      walk_photos: {
        Row: {
          id: string;
          walk_id: string;
          operator_id: string;
          storage_path: string;
          caption: string | null;
          taken_at: string | null;
          created_at: string;
          sha256: string | null;
          byte_size: number | null;
        };
        Insert: {
          id?: string;
          walk_id: string;
          operator_id: string;
          storage_path: string;
          caption?: string | null;
          taken_at?: string | null;
          created_at?: string;
          sha256?: string | null;
          byte_size?: number | null;
        };
        Update: {
          id?: string;
          walk_id?: string;
          operator_id?: string;
          storage_path?: string;
          caption?: string | null;
          taken_at?: string | null;
          created_at?: string;
          sha256?: string | null;
          byte_size?: number | null;
        };
        Relationships: [];
      };
      walks: {
        Row: {
          id: string;
          operator_id: string;
          client_id: string;
          property_id: string;
          service_type_id: string;
          schedule_id: string | null;
          scheduled_date: string;
          window_start: string;
          window_end: string;
          status: Database["public"]["Enums"]["walk_status"];
          started_at: string | null;
          ended_at: string | null;
          credits_debited: number;
          is_overage: boolean;
          distance_m: number | null;
          notes: string | null;
          potty_pee: boolean | null;
          potty_poo: boolean | null;
          fed: boolean | null;
          watered: boolean | null;
          report_sent_at: string | null;
          created_at: string;
          updated_at: string;
          origin_date: string | null;
          cancel_reason: string | null;
          abandoned_at: string | null;
          cost_credits: number | null;
          overage_rate_pence: number | null;
          visit_price_pence: number | null;
        };
        Insert: {
          id?: string;
          operator_id: string;
          client_id: string;
          property_id: string;
          service_type_id: string;
          schedule_id?: string | null;
          scheduled_date: string;
          window_start: string;
          window_end: string;
          status?: Database["public"]["Enums"]["walk_status"];
          started_at?: string | null;
          ended_at?: string | null;
          credits_debited?: number;
          is_overage?: boolean;
          distance_m?: number | null;
          notes?: string | null;
          potty_pee?: boolean | null;
          potty_poo?: boolean | null;
          fed?: boolean | null;
          watered?: boolean | null;
          report_sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
          origin_date?: string | null;
          cancel_reason?: string | null;
          abandoned_at?: string | null;
          cost_credits?: number | null;
          overage_rate_pence?: number | null;
          visit_price_pence?: number | null;
        };
        Update: {
          id?: string;
          operator_id?: string;
          client_id?: string;
          property_id?: string;
          service_type_id?: string;
          schedule_id?: string | null;
          scheduled_date?: string;
          window_start?: string;
          window_end?: string;
          status?: Database["public"]["Enums"]["walk_status"];
          started_at?: string | null;
          ended_at?: string | null;
          credits_debited?: number;
          is_overage?: boolean;
          distance_m?: number | null;
          notes?: string | null;
          potty_pee?: boolean | null;
          potty_poo?: boolean | null;
          fed?: boolean | null;
          watered?: boolean | null;
          report_sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
          origin_date?: string | null;
          cancel_reason?: string | null;
          abandoned_at?: string | null;
          cost_credits?: number | null;
          overage_rate_pence?: number | null;
          visit_price_pence?: number | null;
        };
        Relationships: [];
      };
    };
    Views: {
      v_my_operator: {
        Row: {
          id: string | null;
          display_name: string | null;
          business_name: string | null;
          cancellation_cutoff_hours: number | null;
          gps_retention_days: number | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      fn_account_has_password: {
        Args: {
          p_user: string;
        };
        Returns: boolean;
      };
      fn_adjust_credits: {
        Args: {
          p_client: string;
          p_amount: number;
          p_note: string;
        };
        Returns: number;
      };
      fn_apply_invoice_paid: {
        Args: {
          p_client: string;
          p_credits: number;
          p_invoice_id: string;
          p_amount_pence: number;
          p_currency: string;
          p_receipt_url: string;
          p_is_renewal: boolean;
        };
        Returns: boolean;
      };
      fn_apply_plan_change_intent: {
        Args: {
          p_intent: string;
          p_event_id: string;
        };
        Returns: number;
      };
      fn_apply_rollover: {
        Args: {
          p_client: string;
        };
        Returns: number;
      };
      fn_apply_topup: {
        Args: {
          p_client: string;
          p_credits: number;
          p_payment_intent_id: string;
          p_amount_pence: number;
        };
        Returns: boolean;
      };
      fn_assert_plan_change_intent_tenant: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_assert_tenant_consistency: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_block_invite_log_mutation: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_book_walk: {
        Args: {
          p_property: string;
          p_service: string;
          p_date: string;
          p_window_start: string;
          p_window_end: string;
          p_pet_ids: string[];
        };
        Returns: string;
      };
      fn_cancel_paused_walks: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_change_plan: {
        Args: {
          p_client: string;
          p_new_plan: string;
          p_remaining_fraction: number;
        };
        Returns: number;
      };
      fn_claim_invite: {
        Args: {
          p_token: string;
          p_notice_version: string;
        };
        Returns: Array<{ client_id: string; outcome: Database["public"]["Enums"]["invite_claim_outcome"] }>;
      };
      fn_claim_notification_send: {
        Args: {
          p_id: string;
          p_channel: string;
          p_lease: unknown;
        };
        Returns: string;
      };
      fn_credential_log_block_mutation: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_deactivate_schedule: {
        Args: {
          p_schedule: string;
          p_today: string;
        };
        Returns: unknown;
      };
      fn_debit_walk: {
        Args: {
          p_walk: string;
        };
        Returns: Array<{ outcome: string; cost: number; new_balance: number }>;
      };
      fn_default_walk_origin: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_email_suppressed: {
        Args: {
          p_email: string;
          p_operator: string;
          p_type: Database["public"]["Enums"]["notification_type"];
        };
        Returns: boolean;
      };
      fn_expire_credits: {
        Args: Record<string, never>;
        Returns: number;
      };
      fn_expire_notification_backlog: {
        Args: {
          p_window: unknown;
          p_max_attempts: number;
        };
        Returns: number;
      };
      fn_export_client_data: {
        Args: {
          p_client: string;
        };
        Returns: Json;
      };
      fn_forget_purged_push_subscriptions: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_grant_credits: {
        Args: {
          p_client: string;
          p_amount: number;
          p_note: string;
        };
        Returns: number;
      };
      fn_grant_cycle_credits: {
        Args: {
          p_client: string;
          p_amount: number;
          p_note: string;
          p_invoice_id: string;
        };
        Returns: number;
      };
      fn_guard_clients_update: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_guard_pets_update: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_guard_properties_update: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_guard_walks_client_update: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_invite_signup_allow_attempt: {
        Args: {
          p_token: string;
          p_ip: unknown;
          p_limit: number;
          p_window_seconds: number;
        };
        Returns: boolean;
      };
      fn_invite_signup_check: {
        Args: {
          p_token: string;
          p_email: string;
        };
        Returns: Database["public"]["Enums"]["invite_claim_outcome"];
      };
      fn_is_push_service_endpoint: {
        Args: {
          p_endpoint: string;
        };
        Returns: boolean;
      };
      fn_is_service_session: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      fn_job_health: {
        Args: {
          p_stale_after: unknown;
        };
        Returns: Array<{ job_name: string; last_success: string; age: unknown; stale: boolean }>;
      };
      fn_ledger_apply: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_ledger_block_mutation: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_log_credential_action: {
        Args: {
          p_credential: string;
          p_operator: string;
          p_action: Database["public"]["Enums"]["credential_action"];
          p_purpose: string;
          p_ip: string;
          p_user_agent: string;
          p_walk: string;
        };
        Returns: string;
      };
      fn_materialize_walks: {
        Args: {
          p_horizon_days: number;
        };
        Returns: number;
      };
      fn_note_push_failure: {
        Args: {
          p_id: string;
          p_error: string;
        };
        Returns: unknown;
      };
      fn_notification_backlog: {
        Args: {
          p_window: unknown;
          p_max_attempts: number;
        };
        Returns: Array<{ id: string; email_status: Database["public"]["Enums"]["email_delivery_status"]; email_attempts: number; created_at: string }>;
      };
      fn_notification_claim_lease: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_notify_low_credit: {
        Args: {
          p_client: string;
        };
        Returns: boolean;
      };
      fn_notify_walk_changes: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_operator_can_charge: {
        Args: {
          p_operator: string;
        };
        Returns: boolean;
      };
      fn_preview_invite: {
        Args: {
          p_token: string;
        };
        Returns: Array<{ full_name: string; business_name: string; already_claimed: boolean }>;
      };
      fn_price_unpriced_scheduled_walks: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_purge_client: {
        Args: {
          p_client: string;
        };
        Returns: Array<{ storage_path: string }>;
      };
      fn_purge_client_photos: {
        Args: {
          p_client: string;
        };
        Returns: number;
      };
      fn_read_credential: {
        Args: {
          p_credential: string;
          p_purpose: string;
          p_operator: string;
          p_ip: string;
          p_user_agent: string;
          p_walk: string;
        };
        Returns: Array<{ ciphertext: string; label: string; entry_method: Database["public"]["Enums"]["entry_method"] }>;
      };
      fn_record_plan_change_intent: {
        Args: {
          p_operator: string;
          p_client: string;
          p_requested_by: string;
          p_old_plan: string;
          p_new_plan: string;
          p_subscription: string;
          p_fraction: number;
        };
        Returns: Array<{ o_intent_id: string; o_idempotency_key: string }>;
      };
      fn_refund_cancelled_debit: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_register_push_subscription: {
        Args: {
          p_endpoint: string;
          p_p256dh: string;
          p_auth: string;
          p_user_agent: string;
        };
        Returns: string;
      };
      fn_remove_push_subscription: {
        Args: {
          p_endpoint: string;
        };
        Returns: boolean;
      };
      fn_reset_invite_signup_budget: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_reverse_payment: {
        Args: {
          p_payment: string;
          p_kind: string;
          p_amount_pence: number;
          p_reason: string;
        };
        Returns: Array<{ outcome: string; credits_reversed: number; credits_unrecovered: number; needs_review: boolean }>;
      };
      fn_revoke_credential: {
        Args: {
          p_id: string;
          p_operator: string;
          p_ip: string;
          p_user_agent: string;
        };
        Returns: string;
      };
      fn_revoke_invite: {
        Args: {
          p_client: string;
        };
        Returns: unknown;
      };
      fn_rotate_credential: {
        Args: {
          p_id: string;
          p_operator: string;
          p_ciphertext: string;
          p_entry_method: Database["public"]["Enums"]["entry_method"];
          p_label: string;
          p_ip: string;
          p_user_agent: string;
        };
        Returns: string;
      };
      fn_rotate_invite: {
        Args: {
          p_client: string;
        };
        Returns: string;
      };
      fn_rotate_unsubscribe_token: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_run_nightly_jobs: {
        Args: {
          p_horizon_days: number;
        };
        Returns: Json;
      };
      fn_seed_operator_defaults: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_set_schedule_pets: {
        Args: {
          p_schedule: string;
          p_pet_ids: string[];
        };
        Returns: unknown;
      };
      fn_snapshot_walk_price: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_supersede_settled_failures: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_sweep_abandoned_walks: {
        Args: {
          p_hours: number;
        };
        Returns: number;
      };
      fn_sweep_gps_retention: {
        Args: Record<string, never>;
        Returns: number;
      };
      fn_touch_updated_at: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_unbind_invite: {
        Args: {
          p_client: string;
        };
        Returns: string;
      };
      fn_unsubscribe_by_token: {
        Args: {
          p_token: string;
        };
        Returns: Array<{ o_applied: boolean; o_email: string }>;
      };
      fn_vault_allow_attempt: {
        Args: {
          p_user: string;
          p_ip: unknown;
          p_limit: number;
          p_window_seconds: number;
        };
        Returns: boolean;
      };
      fn_vault_census: {
        Args: {
          p_key_id: string;
        };
        Returns: Array<{ total: number; on_primary: number; on_other: number; unreadable: number }>;
      };
      fn_vault_rewrap_apply: {
        Args: {
          p_id: string;
          p_expect_ciphertext: string;
          p_new_ciphertext: string;
          p_expect_key_id: string;
        };
        Returns: boolean;
      };
      fn_vault_rewrap_batch: {
        Args: {
          p_key_id: string;
          p_limit: number;
        };
        Returns: Array<{ id: string; operator_id: string; ciphertext: string; key_id: string }>;
      };
      fn_vault_set_canary: {
        Args: {
          p_ciphertext: string;
        };
        Returns: string;
      };
      fn_walk_channel_access: {
        Args: {
          p_topic: string;
          p_send: boolean;
        };
        Returns: boolean;
      };
      fn_walk_cost: {
        Args: {
          p_walk: string;
        };
        Returns: number;
      };
      fn_write_credential: {
        Args: {
          p_id: string;
          p_operator: string;
          p_property: string;
          p_entry_method: Database["public"]["Enums"]["entry_method"];
          p_ciphertext: string;
          p_label: string;
          p_ip: string;
          p_user_agent: string;
        };
        Returns: string;
      };
      is_operator: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      my_client_id: {
        Args: Record<string, never>;
        Returns: string;
      };
    };
    Enums: {
      billing_cycle: "weekly" | "monthly";
      client_status: "invited" | "active" | "paused" | "archived";
      credential_action: "read" | "create" | "rotate" | "revoke" | "reauth_failed";
      email_delivery_status: "pending" | "sent" | "skipped" | "failed";
      entry_method: "key_on_file" | "lockbox" | "smart_lock" | "door_code" | "buzzer_fob";
      invite_claim_outcome: "claimed" | "not_found" | "already_claimed" | "expired" | "revoked" | "email_mismatch";
      ledger_entry_type: "grant" | "debit" | "adjust" | "rollover" | "expiry";
      notification_type: "walk_complete" | "low_credit" | "renewal_upcoming" | "payment_failed" | "walk_scheduled" | "walk_cancelled" | "payment_refunded" | "payment_disputed" | "subscription_cancelled" | "plan_changed_externally" | "payment_taken" | "card_saved";
      payment_status: "pending" | "succeeded" | "failed" | "refunded" | "disputed";
      payment_type: "subscription" | "overage" | "topup";
      pet_size: "small" | "medium" | "large" | "giant";
      push_delivery_status: "pending" | "sent" | "skipped" | "failed";
      rollover_policy: "none" | "capped" | "unlimited";
      subscription_status: "none" | "active" | "paused" | "past_due" | "cancelled";
      walk_status: "scheduled" | "in_progress" | "completed" | "cancelled" | "no_show";
    };
    CompositeTypes: Record<string, never>;
  };
};

// ── domain aliases (spec 06) ─────────────────────────────────────────────
export type AccessCredentials = Database["public"]["Tables"]["access_credentials"]["Row"];
export type Clients = Database["public"]["Tables"]["clients"]["Row"];
export type CredentialAccessLog = Database["public"]["Tables"]["credential_access_log"]["Row"];
export type CreditLedger = Database["public"]["Tables"]["credit_ledger"]["Row"];
export type EmailSuppressions = Database["public"]["Tables"]["email_suppressions"]["Row"];
export type InviteClaimAttempts = Database["public"]["Tables"]["invite_claim_attempts"]["Row"];
export type InviteSignupAttempts = Database["public"]["Tables"]["invite_signup_attempts"]["Row"];
export type JobRuns = Database["public"]["Tables"]["job_runs"]["Row"];
export type Notifications = Database["public"]["Tables"]["notifications"]["Row"];
export type Operators = Database["public"]["Tables"]["operators"]["Row"];
export type Payments = Database["public"]["Tables"]["payments"]["Row"];
export type Pets = Database["public"]["Tables"]["pets"]["Row"];
export type PlanChangeIntents = Database["public"]["Tables"]["plan_change_intents"]["Row"];
export type Plans = Database["public"]["Tables"]["plans"]["Row"];
export type Properties = Database["public"]["Tables"]["properties"]["Row"];
export type PushSubscriptions = Database["public"]["Tables"]["push_subscriptions"]["Row"];
export type RecurringSchedules = Database["public"]["Tables"]["recurring_schedules"]["Row"];
export type SchedulePets = Database["public"]["Tables"]["schedule_pets"]["Row"];
export type ServiceTypes = Database["public"]["Tables"]["service_types"]["Row"];
export type StripeEvents = Database["public"]["Tables"]["stripe_events"]["Row"];
export type VaultCanary = Database["public"]["Tables"]["vault_canary"]["Row"];
export type VaultRateLimitAttempts = Database["public"]["Tables"]["vault_rate_limit_attempts"]["Row"];
export type WalkGpsPoints = Database["public"]["Tables"]["walk_gps_points"]["Row"];
export type WalkPets = Database["public"]["Tables"]["walk_pets"]["Row"];
export type WalkPhotos = Database["public"]["Tables"]["walk_photos"]["Row"];
export type Walks = Database["public"]["Tables"]["walks"]["Row"];
export type BillingCycle = Database["public"]["Enums"]["billing_cycle"];
export type ClientStatus = Database["public"]["Enums"]["client_status"];
export type CredentialAction = Database["public"]["Enums"]["credential_action"];
export type EmailDeliveryStatus = Database["public"]["Enums"]["email_delivery_status"];
export type EntryMethod = Database["public"]["Enums"]["entry_method"];
export type InviteClaimOutcome = Database["public"]["Enums"]["invite_claim_outcome"];
export type LedgerEntryType = Database["public"]["Enums"]["ledger_entry_type"];
export type NotificationType = Database["public"]["Enums"]["notification_type"];
export type PaymentStatus = Database["public"]["Enums"]["payment_status"];
export type PaymentType = Database["public"]["Enums"]["payment_type"];
export type PetSize = Database["public"]["Enums"]["pet_size"];
export type PushDeliveryStatus = Database["public"]["Enums"]["push_delivery_status"];
export type RolloverPolicy = Database["public"]["Enums"]["rollover_policy"];
export type SubscriptionStatus = Database["public"]["Enums"]["subscription_status"];
export type WalkStatus = Database["public"]["Enums"]["walk_status"];
