// Generated by scripts/gen-types.py — do not edit by hand.
// Regenerate after every migration phase (docs/dev/local-stack.md).

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      access_credentials: {
        Row: {
          id: string;
          operator_id: string;
          property_id: string;
          entry_method: Database["public"]["Enums"]["entry_method"];
          ciphertext: string;
          label: string | null;
          key_location_hint: string | null;
          rotated_at: string | null;
          revoked_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          operator_id: string;
          property_id: string;
          entry_method: Database["public"]["Enums"]["entry_method"];
          ciphertext: string;
          label?: string | null;
          key_location_hint?: string | null;
          rotated_at?: string | null;
          revoked_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          operator_id?: string;
          property_id?: string;
          entry_method?: Database["public"]["Enums"]["entry_method"];
          ciphertext?: string;
          label?: string | null;
          key_location_hint?: string | null;
          rotated_at?: string | null;
          revoked_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      clients: {
        Row: {
          id: string;
          operator_id: string;
          auth_user_id: string | null;
          full_name: string;
          email: string | null;
          phone: string | null;
          status: Database["public"]["Enums"]["client_status"];
          notes: string | null;
          invite_token: string;
          stripe_customer_id: string | null;
          plan_id: string | null;
          subscription_status: Database["public"]["Enums"]["subscription_status"];
          stripe_subscription_id: string | null;
          credit_balance: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          operator_id: string;
          auth_user_id?: string | null;
          full_name: string;
          email?: string | null;
          phone?: string | null;
          status?: Database["public"]["Enums"]["client_status"];
          notes?: string | null;
          invite_token?: string;
          stripe_customer_id?: string | null;
          plan_id?: string | null;
          subscription_status?: Database["public"]["Enums"]["subscription_status"];
          stripe_subscription_id?: string | null;
          credit_balance?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          operator_id?: string;
          auth_user_id?: string | null;
          full_name?: string;
          email?: string | null;
          phone?: string | null;
          status?: Database["public"]["Enums"]["client_status"];
          notes?: string | null;
          invite_token?: string;
          stripe_customer_id?: string | null;
          plan_id?: string | null;
          subscription_status?: Database["public"]["Enums"]["subscription_status"];
          stripe_subscription_id?: string | null;
          credit_balance?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      credential_access_log: {
        Row: {
          id: string;
          operator_id: string;
          credential_id: string;
          accessed_by: string;
          purpose: string;
          accessed_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          operator_id: string;
          credential_id: string;
          accessed_by: string;
          purpose: string;
          accessed_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          operator_id?: string;
          credential_id?: string;
          accessed_by?: string;
          purpose?: string;
          accessed_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      credit_ledger: {
        Row: {
          id: string;
          seq: number;
          operator_id: string;
          client_id: string;
          entry_type: Database["public"]["Enums"]["ledger_entry_type"];
          amount: number;
          balance_after: number;
          walk_id: string | null;
          expires_at: string | null;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          operator_id: string;
          client_id: string;
          entry_type: Database["public"]["Enums"]["ledger_entry_type"];
          amount: number;
          balance_after: number;
          walk_id?: string | null;
          expires_at?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          operator_id?: string;
          client_id?: string;
          entry_type?: Database["public"]["Enums"]["ledger_entry_type"];
          amount?: number;
          balance_after?: number;
          walk_id?: string | null;
          expires_at?: string | null;
          note?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          operator_id: string;
          client_id: string | null;
          type: Database["public"]["Enums"]["notification_type"];
          title: string;
          body: string | null;
          walk_id: string | null;
          read_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          operator_id: string;
          client_id?: string | null;
          type: Database["public"]["Enums"]["notification_type"];
          title: string;
          body?: string | null;
          walk_id?: string | null;
          read_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          operator_id?: string;
          client_id?: string | null;
          type?: Database["public"]["Enums"]["notification_type"];
          title?: string;
          body?: string | null;
          walk_id?: string | null;
          read_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      operators: {
        Row: {
          id: string;
          business_name: string;
          display_name: string;
          email: string;
          phone: string | null;
          timezone: string;
          currency: string;
          low_credit_threshold: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          business_name: string;
          display_name: string;
          email: string;
          phone?: string | null;
          timezone?: string;
          currency?: string;
          low_credit_threshold?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_name?: string;
          display_name?: string;
          email?: string;
          phone?: string | null;
          timezone?: string;
          currency?: string;
          low_credit_threshold?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          operator_id: string;
          client_id: string;
          walk_id: string | null;
          type: Database["public"]["Enums"]["payment_type"];
          amount_pence: number;
          currency: string;
          stripe_payment_intent_id: string | null;
          stripe_invoice_id: string | null;
          status: Database["public"]["Enums"]["payment_status"];
          receipt_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          operator_id: string;
          client_id: string;
          walk_id?: string | null;
          type: Database["public"]["Enums"]["payment_type"];
          amount_pence: number;
          currency?: string;
          stripe_payment_intent_id?: string | null;
          stripe_invoice_id?: string | null;
          status: Database["public"]["Enums"]["payment_status"];
          receipt_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          operator_id?: string;
          client_id?: string;
          walk_id?: string | null;
          type?: Database["public"]["Enums"]["payment_type"];
          amount_pence?: number;
          currency?: string;
          stripe_payment_intent_id?: string | null;
          stripe_invoice_id?: string | null;
          status?: Database["public"]["Enums"]["payment_status"];
          receipt_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      pets: {
        Row: {
          id: string;
          operator_id: string;
          client_id: string;
          name: string;
          breed: string | null;
          size: Database["public"]["Enums"]["pet_size"] | null;
          temperament: string | null;
          medical_notes: string | null;
          feeding_notes: string | null;
          medication_notes: string | null;
          vet_name: string | null;
          vet_phone: string | null;
          is_reactive: boolean;
          is_escape_risk: boolean;
          photo_path: string | null;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          operator_id: string;
          client_id: string;
          name: string;
          breed?: string | null;
          size?: Database["public"]["Enums"]["pet_size"] | null;
          temperament?: string | null;
          medical_notes?: string | null;
          feeding_notes?: string | null;
          medication_notes?: string | null;
          vet_name?: string | null;
          vet_phone?: string | null;
          is_reactive?: boolean;
          is_escape_risk?: boolean;
          photo_path?: string | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          operator_id?: string;
          client_id?: string;
          name?: string;
          breed?: string | null;
          size?: Database["public"]["Enums"]["pet_size"] | null;
          temperament?: string | null;
          medical_notes?: string | null;
          feeding_notes?: string | null;
          medication_notes?: string | null;
          vet_name?: string | null;
          vet_phone?: string | null;
          is_reactive?: boolean;
          is_escape_risk?: boolean;
          photo_path?: string | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      plans: {
        Row: {
          id: string;
          operator_id: string;
          name: string;
          credits_per_cycle: number;
          price_pence: number;
          cycle: Database["public"]["Enums"]["billing_cycle"];
          rollover_policy: Database["public"]["Enums"]["rollover_policy"];
          rollover_cap: number | null;
          rollover_expiry_days: number | null;
          overage_rate_pence: number;
          stripe_price_id: string | null;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          operator_id: string;
          name: string;
          credits_per_cycle: number;
          price_pence: number;
          cycle: Database["public"]["Enums"]["billing_cycle"];
          rollover_policy?: Database["public"]["Enums"]["rollover_policy"];
          rollover_cap?: number | null;
          rollover_expiry_days?: number | null;
          overage_rate_pence: number;
          stripe_price_id?: string | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          operator_id?: string;
          name?: string;
          credits_per_cycle?: number;
          price_pence?: number;
          cycle?: Database["public"]["Enums"]["billing_cycle"];
          rollover_policy?: Database["public"]["Enums"]["rollover_policy"];
          rollover_cap?: number | null;
          rollover_expiry_days?: number | null;
          overage_rate_pence?: number;
          stripe_price_id?: string | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      properties: {
        Row: {
          id: string;
          operator_id: string;
          client_id: string;
          label: string;
          address_line1: string | null;
          address_line2: string | null;
          city: string | null;
          postcode: string | null;
          access_notes_public: string | null;
          lat: number | null;
          lng: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          operator_id: string;
          client_id: string;
          label: string;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          postcode?: string | null;
          access_notes_public?: string | null;
          lat?: number | null;
          lng?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          operator_id?: string;
          client_id?: string;
          label?: string;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          postcode?: string | null;
          access_notes_public?: string | null;
          lat?: number | null;
          lng?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      recurring_schedules: {
        Row: {
          id: string;
          operator_id: string;
          client_id: string;
          property_id: string;
          service_type_id: string;
          days_of_week: number[];
          window_start: string;
          window_end: string;
          start_date: string;
          end_date: string | null;
          paused_from: string | null;
          paused_until: string | null;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          operator_id: string;
          client_id: string;
          property_id: string;
          service_type_id: string;
          days_of_week: number[];
          window_start: string;
          window_end: string;
          start_date: string;
          end_date?: string | null;
          paused_from?: string | null;
          paused_until?: string | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          operator_id?: string;
          client_id?: string;
          property_id?: string;
          service_type_id?: string;
          days_of_week?: number[];
          window_start?: string;
          window_end?: string;
          start_date?: string;
          end_date?: string | null;
          paused_from?: string | null;
          paused_until?: string | null;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      schedule_pets: {
        Row: {
          schedule_id: string;
          pet_id: string;
          operator_id: string;
          created_at: string;
        };
        Insert: {
          schedule_id: string;
          pet_id: string;
          operator_id: string;
          created_at?: string;
        };
        Update: {
          schedule_id?: string;
          pet_id?: string;
          operator_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      service_types: {
        Row: {
          id: string;
          operator_id: string;
          name: string;
          duration_minutes: number;
          credit_cost: number;
          weekend_surcharge_credits: number;
          is_default: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          operator_id: string;
          name: string;
          duration_minutes: number;
          credit_cost: number;
          weekend_surcharge_credits?: number;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          operator_id?: string;
          name?: string;
          duration_minutes?: number;
          credit_cost?: number;
          weekend_surcharge_credits?: number;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      stripe_events: {
        Row: {
          id: string;
          type: string;
          payload: Json | null;
          processed_at: string;
          created_at: string;
        };
        Insert: {
          id: string;
          type: string;
          payload?: Json | null;
          processed_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          type?: string;
          payload?: Json | null;
          processed_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      walk_gps_points: {
        Row: {
          id: string;
          walk_id: string;
          operator_id: string;
          recorded_at: string;
          lat: number;
          lng: number;
          accuracy_m: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          walk_id: string;
          operator_id: string;
          recorded_at: string;
          lat: number;
          lng: number;
          accuracy_m?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          walk_id?: string;
          operator_id?: string;
          recorded_at?: string;
          lat?: number;
          lng?: number;
          accuracy_m?: number | null;
          created_at?: string;
        };
        Relationships: [];
      };
      walk_pets: {
        Row: {
          walk_id: string;
          pet_id: string;
          operator_id: string;
          created_at: string;
        };
        Insert: {
          walk_id: string;
          pet_id: string;
          operator_id: string;
          created_at?: string;
        };
        Update: {
          walk_id?: string;
          pet_id?: string;
          operator_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      walk_photos: {
        Row: {
          id: string;
          walk_id: string;
          operator_id: string;
          storage_path: string;
          caption: string | null;
          taken_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          walk_id: string;
          operator_id: string;
          storage_path: string;
          caption?: string | null;
          taken_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          walk_id?: string;
          operator_id?: string;
          storage_path?: string;
          caption?: string | null;
          taken_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      walks: {
        Row: {
          id: string;
          operator_id: string;
          client_id: string;
          property_id: string;
          service_type_id: string;
          schedule_id: string | null;
          scheduled_date: string;
          window_start: string;
          window_end: string;
          status: Database["public"]["Enums"]["walk_status"];
          started_at: string | null;
          ended_at: string | null;
          credits_debited: number;
          is_overage: boolean;
          distance_m: number | null;
          notes: string | null;
          potty_pee: boolean | null;
          potty_poo: boolean | null;
          fed: boolean | null;
          watered: boolean | null;
          report_sent_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          operator_id: string;
          client_id: string;
          property_id: string;
          service_type_id: string;
          schedule_id?: string | null;
          scheduled_date: string;
          window_start: string;
          window_end: string;
          status?: Database["public"]["Enums"]["walk_status"];
          started_at?: string | null;
          ended_at?: string | null;
          credits_debited?: number;
          is_overage?: boolean;
          distance_m?: number | null;
          notes?: string | null;
          potty_pee?: boolean | null;
          potty_poo?: boolean | null;
          fed?: boolean | null;
          watered?: boolean | null;
          report_sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          operator_id?: string;
          client_id?: string;
          property_id?: string;
          service_type_id?: string;
          schedule_id?: string | null;
          scheduled_date?: string;
          window_start?: string;
          window_end?: string;
          status?: Database["public"]["Enums"]["walk_status"];
          started_at?: string | null;
          ended_at?: string | null;
          credits_debited?: number;
          is_overage?: boolean;
          distance_m?: number | null;
          notes?: string | null;
          potty_pee?: boolean | null;
          potty_poo?: boolean | null;
          fed?: boolean | null;
          watered?: boolean | null;
          report_sent_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      v_my_operator: {
        Row: {
          id: string | null;
          display_name: string | null;
          business_name: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      fn_adjust_credits: {
        Args: {
          p_client: string;
          p_amount: number;
          p_note: string;
        };
        Returns: number;
      };
      fn_apply_rollover: {
        Args: {
          p_client: string;
        };
        Returns: number;
      };
      fn_change_plan: {
        Args: {
          p_client: string;
          p_new_plan: string;
          p_remaining_fraction: number;
        };
        Returns: number;
      };
      fn_claim_invite: {
        Args: {
          p_token: string;
        };
        Returns: string;
      };
      fn_debit_walk: {
        Args: {
          p_walk: string;
        };
        Returns: Array<{ outcome: string; cost: number; new_balance: number }>;
      };
      fn_expire_credits: {
        Args: Record<string, never>;
        Returns: number;
      };
      fn_grant_credits: {
        Args: {
          p_client: string;
          p_amount: number;
          p_note: string;
        };
        Returns: number;
      };
      fn_guard_clients_update: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_guard_pets_update: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_guard_properties_update: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_is_service_session: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      fn_ledger_apply: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_ledger_block_mutation: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_notify_low_credit: {
        Args: {
          p_client: string;
        };
        Returns: boolean;
      };
      fn_read_credential: {
        Args: {
          p_credential: string;
          p_purpose: string;
          p_operator: string;
        };
        Returns: Array<{ ciphertext: string; label: string; entry_method: Database["public"]["Enums"]["entry_method"] }>;
      };
      fn_seed_operator_defaults: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_touch_updated_at: {
        Args: Record<string, never>;
        Returns: unknown;
      };
      fn_walk_cost: {
        Args: {
          p_walk: string;
        };
        Returns: number;
      };
      is_operator: {
        Args: Record<string, never>;
        Returns: boolean;
      };
      my_client_id: {
        Args: Record<string, never>;
        Returns: string;
      };
    };
    Enums: {
      billing_cycle: "weekly" | "monthly";
      client_status: "invited" | "active" | "paused" | "archived";
      entry_method: "key_on_file" | "lockbox" | "smart_lock" | "door_code" | "buzzer_fob";
      ledger_entry_type: "grant" | "debit" | "adjust" | "rollover" | "expiry";
      notification_type: "walk_complete" | "low_credit" | "renewal_upcoming" | "payment_failed" | "walk_scheduled" | "walk_cancelled";
      payment_status: "pending" | "succeeded" | "failed" | "refunded";
      payment_type: "subscription" | "overage" | "topup";
      pet_size: "small" | "medium" | "large" | "giant";
      rollover_policy: "none" | "capped" | "unlimited";
      subscription_status: "none" | "active" | "paused" | "past_due" | "cancelled";
      walk_status: "scheduled" | "in_progress" | "completed" | "cancelled" | "no_show";
    };
    CompositeTypes: Record<string, never>;
  };
};

// ── domain aliases (spec 06) ─────────────────────────────────────────────
export type AccessCredentials = Database["public"]["Tables"]["access_credentials"]["Row"];
export type Clients = Database["public"]["Tables"]["clients"]["Row"];
export type CredentialAccessLog = Database["public"]["Tables"]["credential_access_log"]["Row"];
export type CreditLedger = Database["public"]["Tables"]["credit_ledger"]["Row"];
export type Notifications = Database["public"]["Tables"]["notifications"]["Row"];
export type Operators = Database["public"]["Tables"]["operators"]["Row"];
export type Payments = Database["public"]["Tables"]["payments"]["Row"];
export type Pets = Database["public"]["Tables"]["pets"]["Row"];
export type Plans = Database["public"]["Tables"]["plans"]["Row"];
export type Properties = Database["public"]["Tables"]["properties"]["Row"];
export type RecurringSchedules = Database["public"]["Tables"]["recurring_schedules"]["Row"];
export type SchedulePets = Database["public"]["Tables"]["schedule_pets"]["Row"];
export type ServiceTypes = Database["public"]["Tables"]["service_types"]["Row"];
export type StripeEvents = Database["public"]["Tables"]["stripe_events"]["Row"];
export type WalkGpsPoints = Database["public"]["Tables"]["walk_gps_points"]["Row"];
export type WalkPets = Database["public"]["Tables"]["walk_pets"]["Row"];
export type WalkPhotos = Database["public"]["Tables"]["walk_photos"]["Row"];
export type Walks = Database["public"]["Tables"]["walks"]["Row"];
export type BillingCycle = Database["public"]["Enums"]["billing_cycle"];
export type ClientStatus = Database["public"]["Enums"]["client_status"];
export type EntryMethod = Database["public"]["Enums"]["entry_method"];
export type LedgerEntryType = Database["public"]["Enums"]["ledger_entry_type"];
export type NotificationType = Database["public"]["Enums"]["notification_type"];
export type PaymentStatus = Database["public"]["Enums"]["payment_status"];
export type PaymentType = Database["public"]["Enums"]["payment_type"];
export type PetSize = Database["public"]["Enums"]["pet_size"];
export type RolloverPolicy = Database["public"]["Enums"]["rollover_policy"];
export type SubscriptionStatus = Database["public"]["Enums"]["subscription_status"];
export type WalkStatus = Database["public"]["Enums"]["walk_status"];
