#!/usr/bin/env python3
"""Generate app/src/lib/types.ts from the local database.

Stand-in for `supabase gen types typescript --local` on the no-Docker stack
(docs/dev/local-stack.md): introspects information_schema + pg_enum and
emits the supabase-js `Database` shape. Run after every migration phase:

    python3 scripts/gen-types.py
"""
import json
import os
import subprocess
import sys

DB_URL = os.environ.get("LOCAL_DB_URL", "postgresql://postgres@127.0.0.1:54322/postgres")
OUT = os.path.join(os.path.dirname(__file__), "..", "app", "src", "lib", "types.ts")


def q(sql: str):
    out = subprocess.run(
        ["psql", DB_URL, "-t", "-A", "-c", sql],
        capture_output=True, text=True, check=True,
    ).stdout.strip()
    return [json.loads(line) for line in out.splitlines() if line.strip()]


ENUMS = q("""
  select json_build_object('name', t.typname, 'values',
    (select json_agg(e.enumlabel order by e.enumsortorder)
       from pg_enum e where e.enumtypid = t.oid))
  from pg_type t
  join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public' and t.typtype = 'e'
  order by t.typname
""")
ENUM_NAMES = {e["name"] for e in ENUMS}

COLUMNS = q("""
  select json_build_object(
    'table', c.table_name, 'kind', tt.table_type, 'column', c.column_name,
    'udt', c.udt_name, 'nullable', c.is_nullable = 'YES',
    'has_default', c.column_default is not null,
    'identity_always', c.is_identity = 'YES' and c.identity_generation = 'ALWAYS',
    'generated', c.is_generated = 'ALWAYS',
    'position', c.ordinal_position)
  from information_schema.columns c
  join information_schema.tables tt
    on tt.table_schema = c.table_schema and tt.table_name = c.table_name
  where c.table_schema = 'public'
  order by c.table_name, c.ordinal_position
""")

FUNCTIONS = q("""
  select json_build_object(
    'name', p.proname,
    'args', coalesce((
      select json_agg(json_build_object(
        'name', a.name, 'type', a.typ, 'mode', a.mode) order by a.ord)
      from unnest(
        coalesce(p.proargnames, array[]::text[]),
        coalesce(p.proallargtypes::regtype[]::text[],
                 p.proargtypes::regtype[]::text[]),
        case when p.proargmodes is null
             then array_fill('i'::text, array[p.pronargs])
             else p.proargmodes::text[] end
      ) with ordinality as a(name, typ, mode, ord)), '[]'::json),
    'returns', pg_get_function_result(p.oid),
    'retset', p.proretset)
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and (p.proname like 'fn\\_%' or p.proname in ('is_operator', 'my_client_id'))
    and p.prokind = 'f'
  order by p.proname
""")

SCALAR = {
    "uuid": "string", "text": "string", "bpchar": "string", "varchar": "string",
    "int2": "number", "int4": "number", "int8": "number", "numeric": "number",
    "float4": "number", "float8": "number", "bool": "boolean",
    "timestamptz": "string", "timestamp": "string", "date": "string",
    "time": "string", "timetz": "string", "jsonb": "Json", "json": "Json",
    "bytea": "string",
}


def ts_type(udt: str) -> str:
    if udt.startswith("_"):
        return ts_type(udt[1:]) + "[]"
    if udt in ENUM_NAMES:
        return f'Database["public"]["Enums"]["{udt}"]'
    return SCALAR.get(udt, "unknown")


def sql_type_to_ts(t: str) -> str:
    t = t.strip()
    if t.endswith("[]"):
        return sql_type_to_ts(t[:-2]) + "[]"
    m = {
        "uuid": "string", "text": "string", "character": "string",
        "integer": "number", "bigint": "number", "numeric": "number",
        "boolean": "boolean", "timestamp with time zone": "string",
        "date": "string", "time without time zone": "string",
        "double precision": "number", "real": "number", "bytea": "string",
        "jsonb": "Json",
    }
    if t in ENUM_NAMES:
        return f'Database["public"]["Enums"]["{t}"]'
    return m.get(t, "unknown")


tables: dict = {}
for c in COLUMNS:
    t = tables.setdefault(c["table"], {"kind": c["kind"], "cols": []})
    t["cols"].append(c)

lines: list = []
w = lines.append
w("// Generated by scripts/gen-types.py — do not edit by hand.")
w("// Regenerate after every migration phase (docs/dev/local-stack.md).")
w("")
w("export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];")
w("")
# NOTE: must be a type alias, not an interface — interfaces have no implicit
# index signature and supabase-js's generics would resolve to `never`.
w("export type Database = {")
w("  public: {")
w("    Tables: {")
for name in sorted(k for k, v in tables.items() if v["kind"] == "BASE TABLE"):
    cols = tables[name]["cols"]
    w(f"      {name}: {{")
    w("        Row: {")
    for c in cols:
        t = ts_type(c["udt"]) + (" | null" if c["nullable"] else "")
        w(f'          {c["column"]}: {t};')
    w("        };")
    w("        Insert: {")
    for c in cols:
        if c["identity_always"] or c["generated"]:
            continue
        opt = "?" if (c["has_default"] or c["nullable"]) else ""
        t = ts_type(c["udt"]) + (" | null" if c["nullable"] else "")
        w(f'          {c["column"]}{opt}: {t};')
    w("        };")
    w("        Update: {")
    for c in cols:
        if c["identity_always"] or c["generated"]:
            continue
        t = ts_type(c["udt"]) + (" | null" if c["nullable"] else "")
        w(f'          {c["column"]}?: {t};')
    w("        };")
    w("        Relationships: [];")
    w("      };")
w("    };")
w("    Views: {")
for name in sorted(k for k, v in tables.items() if v["kind"] == "VIEW"):
    cols = tables[name]["cols"]
    w(f"      {name}: {{")
    w("        Row: {")
    for c in cols:
        w(f'          {c["column"]}: {ts_type(c["udt"])} | null;')
    w("        };")
    w("        Relationships: [];")
    w("      };")
w("    };")
w("    Functions: {")
for f in FUNCTIONS:
    ins = [a for a in f["args"] if a["mode"] in ("i", "b")]
    outs = [a for a in f["args"] if a["mode"] in ("o", "t", "b")]
    w(f'      {f["name"]}: {{')
    if ins:
        w("        Args: {")
        for a in ins:
            w(f'          {a["name"]}: {sql_type_to_ts(a["type"])};')
        w("        };")
    else:
        w("        Args: Record<string, never>;")
    if f["retset"] and outs:
        row = "; ".join(f'{a["name"]}: {sql_type_to_ts(a["type"])}' for a in outs)
        w(f"        Returns: Array<{{ {row} }}>;")
    else:
        w(f'        Returns: {sql_type_to_ts(f["returns"])};')
    w("      };")
w("    };")
w("    Enums: {")
for e in ENUMS:
    vals = " | ".join(f'"{v}"' for v in e["values"])
    w(f'      {e["name"]}: {vals};')
w("    };")
w("    CompositeTypes: Record<string, never>;")
w("  };")
w("};")
w("")
w("// ── domain aliases (spec 06) ─────────────────────────────────────────────")
for name in sorted(k for k, v in tables.items() if v["kind"] == "BASE TABLE"):
    alias = "".join(p.capitalize() for p in name.split("_"))
    w(f'export type {alias} = Database["public"]["Tables"]["{name}"]["Row"];')
for e in ENUMS:
    alias = "".join(p.capitalize() for p in e["name"].split("_"))
    w(f'export type {alias} = Database["public"]["Enums"]["{e["name"]}"];')
w("")

os.makedirs(os.path.dirname(os.path.abspath(OUT)), exist_ok=True)
with open(OUT, "w") as fh:
    fh.write("\n".join(lines))
print(f"wrote {os.path.relpath(OUT)} ({len(lines)} lines)", file=sys.stderr)
