#!/usr/bin/env python3
"""Regenerate spec 03's SECURITY DEFINER catalogue from the migrations.

Review H21: the catalogue was hand-maintained, presented as "the complete
grant-audit checklist", and listed 11 functions out of 52. An engineer adding a
definer function and checking their grants against it had no idea 41 peers
existed — which is the opposite of what a checklist is for.

A hand-maintained list of 52 entries would rot again by the next migration, so
it is generated instead, and CI asserts the committed file matches (the same
shape as the `gen-types.py` drift check). Adding a definer function without
regenerating fails the build, and the failure names the function.

The grants are read from the migrations rather than from a live database on
purpose: this runs in CI with no Postgres service in the frontend job, and the
migrations are the append-only source of truth that a `db push` will apply.

Writes between the markers in docs/spec/03-security-model.md. Idempotent.
"""
from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MIGRATIONS = ROOT / "supabase" / "migrations"
SPEC = ROOT / "docs" / "spec" / "03-security-model.md"

BEGIN = "<!-- BEGIN GENERATED DEFINER CATALOG -->"
END = "<!-- END GENERATED DEFINER CATALOG -->"

# `create [or replace] function name(args) ... returns` — args may span lines
# and contain nested parens (e.g. numeric(10,2)), so the header is taken up to
# the last `)` before `returns`.
CREATE = re.compile(
    r"create\s+(?:or\s+replace\s+)?function\s+(?:public\.)?([a-z0-9_]+)\s*\(",
    re.I,
)
GRANT = re.compile(
    r"grant\s+execute\s+on\s+function\s+(?:public\.)?([a-z0-9_]+)\s*\([^;]*?\)\s*to\s+([^;]+);",
    re.I | re.S,
)


def strip_sql_comments(sql: str) -> str:
    """`--` to end of line, and /* */ blocks. A commented-out grant is not a
    grant, and a commented-out create is not a function."""
    sql = re.sub(r"/\*.*?\*/", "", sql, flags=re.S)
    return re.sub(r"--[^\n]*", "", sql)


def function_body_after(sql: str, start: int) -> str:
    """Everything from a create-function header to the end of its body, bounded
    by the next `create ... function` so one function's SET cannot be read as
    another's."""
    nxt = CREATE.search(sql, start + 1)
    return sql[start : nxt.start() if nxt else len(sql)]


def collect() -> tuple[dict[str, bool], dict[str, set[str]], list[str]]:
    """-> (name -> is_definer for its LAST definition, name -> granted roles,
    migration order)."""
    definer: dict[str, bool] = {}
    grants: dict[str, set[str]] = {}
    order: list[str] = []
    for path in sorted(MIGRATIONS.glob("*.sql")):
        sql = strip_sql_comments(path.read_text())
        for m in CREATE.finditer(sql):
            name = m.group(1)
            chunk = function_body_after(sql, m.start())
            # Last definition wins: `create or replace` in a later migration is
            # what Postgres actually has. Reading the first would describe a
            # function that no longer exists — the same trap the payment-status
            # index parser had to avoid.
            definer[name] = bool(re.search(r"security\s+definer", chunk, re.I))
            if name not in order:
                order.append(name)
        for m in GRANT.finditer(sql):
            name = m.group(1)
            roles = {r.strip() for r in m.group(2).split(",") if r.strip()}
            grants.setdefault(name, set()).update(roles)
    return definer, grants, order


def render(definer: dict[str, bool], grants: dict[str, set[str]], order: list[str]) -> str:
    names = [n for n in order if definer.get(n)]
    lines = [
        BEGIN,
        "",
        f"{len(names)} `SECURITY DEFINER` functions, in migration order. Generated by",
        "`scripts/gen-definer-catalog.py`; CI fails if this table and the migrations",
        "disagree, so adding a definer function without regenerating breaks the build.",
        "",
        "*Granted to* is the union of every `GRANT EXECUTE` across all migrations for",
        "that name. **none** means no API role can call it — service-role and other",
        "definer functions only, which is the correct default.",
        "",
        "| Function | EXECUTE granted to |",
        "|---|---|",
    ]
    for name in names:
        roles = sorted(grants.get(name, set()))
        # service_role holds BYPASSRLS and is granted table-wide, so listing it
        # per function says nothing; what matters is which API role can reach in.
        api = [r for r in roles if r in ("authenticated", "anon", "public")]
        shown = ", ".join(f"`{r}`" for r in api) if api else "**none**"
        lines.append(f"| `{name}` | {shown} |")
    lines += ["", END]
    return "\n".join(lines)


def main() -> int:
    definer, grants, order = collect()
    block = render(definer, grants, order)
    spec = SPEC.read_text()
    if BEGIN in spec and END in spec:
        updated = re.sub(
            re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block, spec, flags=re.S
        )
    else:
        print(f"FAIL: {SPEC} has no generated-catalog markers", file=sys.stderr)
        return 1
    if updated != spec:
        SPEC.write_text(updated)
    count = sum(1 for n in order if definer.get(n))
    print(f"{count} SECURITY DEFINER functions catalogued in {SPEC.relative_to(ROOT)}")
    if any(r in grants.get(n, set()) for n in order if definer.get(n) for r in ("anon", "public")):
        print("FAIL: a definer function grants EXECUTE to anon or PUBLIC", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
